name: exmag
loss_type: l2
reg_type: l1
a_reg_type: l1
lambda1: 1.0
lambda2: 1.0
nonzero_threshold: 0.001
callback_mode: all_cycles
robust: false
weights_bound: 100.0
time_limit: 1800
target_mip_gap: 0.01
exmag_version: version2 # version0 version2
note: gurobi13

