# config.yaml

data_dir: datasets/syntheticdata
out_dir: results/exdbn
num_workers: 4

generate:
  features_list: [5, 10, 15, 20, 25, 30, 35]
  n_samples: 2000

solver:
  lambda1: 1.0
  lambda2: 1.0
  max_degrees: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35]
  sample_sizes: [20, 200, 2000]
  time_limit: 18000
  constraints_mode: weights
  callback_mode: all_cycles
  loss_type: l2
  reg_type: l1
  a_reg_type: l1
  robust: false
  weights_bound: 100.0
  target_mip_gap: 0.001
