
hydra:
  launcher:
    n_jobs: 1
    prefer: processes
#    prefer: processes # use processes instead of threads
#    backend: multiprocessing # use multiprocessing backend instead of loky
  sweeper:
    # max_batch_size: 500 # - only for cluster
    params:
      #scenario:
      #distribution_coefficient: 1,2,3,4
experiment: DAGS article
tracking: mlflow
plot: true
plot_dpi: [50, 300]
defaults:
  - solver: milp
  - problem: path
  - override hydra/launcher: joblib
  - _self_




